image: gradle:8.3-jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # ensure Gradle uses a project-local cache and that the directory exists and is writable
  - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradle"
  - mkdir -p "$GRADLE_USER_HOME"
  - chmod -R 0777 "$GRADLE_USER_HOME"

stages:
  - build
  - unit_test
  - int_test

build:
  stage: build
  script:
    - echo "Building the application..."
    - "gradle clean build -x test"
  only: 
    - develop 
    - main

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests..."
    - "gradle test"
  only: 
    - develop 
    - main

int_test:
  stage: int_test
  script:
    - echo "Running integration tests..."
    - "gradle integrationTest"
  allow_failure: true
  only: 
    - develop 
    - main
