image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - unit_test

build:
  stage: build
  script:
    - echo "Building the application..."
    - "gradle clean build -x test"

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests..."
    - "gradle test"

int_test:
  stage: int_test
  script:
    - echo "Running integration tests..."
    - "gradle integrationTest"
