image: gradle:8.3-jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -Xms512m'"
  GRADLE_TERMS_OF_SERVICE_ACCEPTED: "yes"

before_script:
  - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradle"
  - rm -rf "$GRADLE_USER_HOME/caches"
  - mkdir -p "$GRADLE_USER_HOME"
  - chmod -R 0777 "$GRADLE_USER_HOME"

stages:
  - build
  - unit_test
  - int_test

build:
  stage: build
  script:
    - echo "Building the application..."
    - "gradle build -x test --scan"
  only: 
    - develop 
    - main

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests..."
    - "gradle test"
  only: 
    - develop 
    - main

int_test:
  stage: int_test
  script:
    - echo "Running integration tests..."
    - "gradle integrationTest"
  allow_failure: true
  only: 
    - develop 
    - main
