quarkus:
  camel:
    context:
      name: vicuna-hexa-kotlin
    openapi:
      expose:
        enabled: true
    rest:
      inline-routes: true
  http:
    cors:
      origins: /.*/
    http2: false
    access-log:
      enabled: true
    port: 8089
    auth:
      permission:
        authenticated:
          paths:  /*
          policy: authenticated
  datasource:
    db-kind: h2
  hibernate-orm:
    database:
      generation: none
  liquibase:
    migrate-at-start: true
    change-log: db/db.changelog-master.yaml
  oidc:
    auth-server-url: http://localhost:8180/realms/development
    client-id: backend-service
    credentials:
      secret: qQOkEGGd6JzzeDj0wkqjTFzrHdJiWdgz
#kafka:
#   bootstrap:
#     servers: localhost:29092
mp:
  messaging:
    outgoing:
      users-out:
        connector: smallrye-kafka
        topic: user-out
    incoming:
      users-in:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        topic: user-in

  openapi:
   scan:
      disable: false
  log:
    category:
      "io.quarkus.category":
        level: INFO

  smallrye-openapi:
    security-scheme: implicit